runner:
  scene_name: showcase
renderer:
  recursion_depth: 3
phong:
  shadows: true
  fresnel: true
  dispersion: true
metal_rough:
  normal_mapping: false
  nearest_neighbor_estimation: false
  bsdf_importance_sampling: false
  russian_roulette: false